config/routes.rb
Rails.application.routes.draw do
root 'users#home'

  resources :musicians  , only: [:index]
  get 'users/updatepassword', :to => 'users#updatepassword'
  resources :users do
    resources :equipment, only: [:new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:new, :create, :update, :destroy] do
      resources :reviews, only:[:new, :create, :index]
    end
  end

  get '/bookings/:user_id/new/confirmation' => 'bookings#confirmation'
  get '/bookings/new' => 'bookings#new_no_musician'
  get '/bookings/map' => 'bookings#map'
  get '/bookings/musicians_in_radius' => 'bookings#musicians_in_radius'

  post '/bookings/search_musicians' => 'bookings#search_musicians'

  resources :sessions, only: [:new, :create]
  delete 'logout' => 'sessions#destroy'



end

app/models/equipment.rb
class Equipment < ApplicationRecord
  CATEGORY_OPTIONS = [
    "Soundboard / PA",
    "Lighting Rig"
  ]

  belongs_to :musician, class_name: 'User'
  has_and_belongs_to_many :bookings
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :ensure_owner

  def new
    @equipment = Equipment.new
    @musician = User.find(params[:user_id])
  end

  def create
    @equipment = Equipment.new(equipment_params)
    @equipment.musician = current_user
    if @equipment.save
      respond_to do |format|
        format.html { redirect_to user_path(current_user) }
        format.js {}
      end
      flash[:notice] = "Successfully added equipment to your profile"
    else
      flash.now[:alert] = @equipment.errors.full_messages
      render "new"
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  def equipment_params
    params.require(:equipment).permit(:category, :details, :price)
  end

  def ensure_owner
    @musician = User.find(params[:user_id])
    if session[:user_id] != @musician.id
      flash[:alert] = ["You cannot add equipment to an account you don't own"]
      redirect_to users_url
    end
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_new_equipment.html.erb
<p><strong>Item: </strong><%= @equipment.category %></p>
<p><strong>Details: </strong><%= @equipment.details %></p>
<p><strong>Cost to include: </strong>$<%= @equipment.price %></p>
<%= link_to 'Remove', user_equipment_path(@equipment), method: :delete %>

app/views/equipment/create.js.erb
$('.equipment').append("<%= j render partial: 'new_equipment', locals: { equipment: @equipment } %>")

app/views/equipment/new.html.erb
<div class= 'new-equipment'>
<% if @equipment.errors %>
  <% @equipment.errors.messages.each do |key, value|  %>
    <% value.each do |error| %>
      <%= error %>
    <% end %>
  <% end %>
<% end %>

<%= form_for [@musician, @equipment] do |f| %>

  <p>
    <%= f.label :category, "Type of Equipment" %>
    <%= f.select :category, options_for_select(Equipment::CATEGORY_OPTIONS) %>
  </p>

  <p>
    <%= f.label :details %>
    <%= f.text_area :details, rows: "5", placeholder: "eg: Mackie 24-channel 1500W with sub" %>
  </p>

  <p>
    <%= f.label :price, "Cost to include" %>
    <%= f.number_field :price, placeholder: "Your price to bring this to a gig - enter only a number" %>
  </p>

  <%= f.submit 'Save to My Equipment', class: "btn" %>

<% end %>

</div>