config/routes.rb
Rails.application.routes.draw do
root 'users#home'

  resources :musicians  , only: [:index]
  get 'users/updatepassword', :to => 'users#updatepassword'
  resources :users do
    resources :equipment, only: [:new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:new, :create, :update, :destroy] do
      resources :reviews, only:[:new, :create, :index]
    end
  end

  get '/bookings/:user_id/new/confirmation' => 'bookings#confirmation'
  get '/bookings/new' => 'bookings#new_no_musician'
  get '/bookings/map' => 'bookings#map'
  get '/bookings/musicians_in_radius' => 'bookings#musicians_in_radius'

  post '/bookings/search_musicians' => 'bookings#search_musicians'

  resources :sessions, only: [:new, :create]
  delete 'logout' => 'sessions#destroy'



end

app/models/booking.rb
class Booking < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  belongs_to :musician, class_name: 'User'
  belongs_to :client, class_name: 'User'
  has_one :review
  has_and_belongs_to_many :equipment

  validates :address, :event_name, presence: true
  validate :start_time_cannot_be_in_time_past
  validate :end_time_must_be_after_start
  validate :booking_address_must_be_valid

  def start_time_cannot_be_in_time_past
    if self[:start_time] < Time.now
      errors.add(:start_time, "The start date cannot be in the past. Please try again.")
    end
  end

  def end_time_must_be_after_start
    if self[:end_time] <= self[:start_time]
        errors.add(:end_time, "Please choose an end time after the start time.")
    end
  end

  def booking_address_must_be_valid
    results = Geocoder.search(self[:address])
    unless results.any?
      errors.add(:address, 'must be valid')
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Serializers::JSON
  geocoded_by :address
  after_validation :geocode
  # mount_uploader :profile_picture, ProfilePictureUploader
  has_secure_password

  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validates :kind, :presence => { message: 'specify if you are a musician or an event planner!' }
  validates :act_type, presence: true, if: :user_type_is_musician?
  validates :hourly_rate, presence: true, if: :user_type_is_musician?
  validates :hourly_rate, numericality: { greater_than: 0 }, if: :user_type_is_musician?
  validate :kind_must_only_be_musician_or_client
  validate :musician_act_type_can_only_be_dj_or_band, if: :user_type_is_musician?
  validate :musician_address_must_be_valid, if: :user_type_is_musician?

  has_many :gigs, class_name: 'Booking', foreign_key: :musician_id
  has_many :events, class_name: 'Booking', foreign_key: :client_id
  has_many :musician_reviews, class_name:'Review', foreign_key: :musician_id
  has_many :client_reviews, class_name:'Review', foreign_key: :client_id
  has_many :equipment, foreign_key: :musician_id

  has_and_belongs_to_many :genres

  def kind_must_only_be_musician_or_client
    if self[:kind] != 'musician' && self[:kind] != 'client'
      errors.add(:kind, "can only be 'musician' or 'client'")
    end
  end

  def musician_act_type_can_only_be_dj_or_band
    if self[:act_type] != 'dj' && self[:act_type] != 'band'
      errors.add(:act_type, "can only be 'dj' or 'band'")
    end
  end

  def musician_address_must_be_valid
    results = Geocoder.search(self[:address])
    unless results.any?
      errors.add(:address, 'must be valid')
    end
  end

  def user_type_is_musician?
    if self[:kind] == 'musician'
      return true
    else
      return false
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  require 'json'
  skip_before_action :verify_authenticity_token

  def new
    @booking = Booking.new
    @musician = User.find(params[:user_id])
  end

  def new_no_musician
    @booking = Booking.new
    @booking.client = current_user
    @genres = Genre.all
  end

  def search_musicians
    @booking = Booking.new(booking_params)
    @musicians = SearchMusicians.new(params).results
    render 'find_musicians', layout: false
  end

  def musicians_in_radius
    @musicians = User.where('kind = ?', 'musician')
    respond_to do |format|
      format.json {render :json => @musicians}
    end
  end

  def confirmation
    @booking = Booking.new(booking_params)
    @musician = User.find(params[:user_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @musician = User.find(params[:user_id])
    @booking.musician = @musician
    @booking.client = current_user
    if @booking.save
      redirect_to user_url(current_user)
    else
      flash.now[:alert] = @booking.errors.full_messages
      render "new"
    end
  end

  def update
    Booking.find(params[:id]).update(confirmed: true)
    render json: {status: 'okay'}
  end

  def destroy
    Booking.find(params[:id]).delete
    render json: {status: 'okay'}
  end

  def map
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :address, :party_size, :age_range, :event_name, equipment_ids: [])
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking_form.html.erb
<h3><%= musician.act_type.capitalize %> name: <%= musician.stage_name %></h3>

<p>Artist rate: $<span id="artist-hourly-rate"><%= musician.hourly_rate.to_i %></span>/hr</p>

<% if musician.equipment.any? %>
  <p>This artist has equipment available - see below</p>
<% end %>

<%= form_for [musician, booking] do |f| %>

  <%= f.label :event_name %>
  <%= f.text_field :event_name, placeholder: "eg: 'McArthur Wedding', 'Company B Summer Jam'" %>

  <%= f.label :start_time %>
  <%= f.datetime_select :start_time, :ampm => true, :minute_step => 15 %>

  <%= f.label :end_time %>
  <%= f.datetime_select :end_time, :ampm => true, :minute_step => 15 %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :party_size %>
  <%= f.number_field :party_size, placeholder: "Approximate attendance at your event - enter only a number" %>

  <%= f.label :age_range %>
  <%= f.text_field :age_range, placeholder: "eg: '19+', 'all ages', '25 - 55'" %>

  <% if musician.equipment.any? %>
    <div class="equipment_booking">
      <%= field_set_tag 'Equipment this artist can bring' do %>
        <% collection_check_boxes(:booking, :equipment_ids, musician.equipment, :id, :category) do |checkbox| %>
          <div class="form-check2">
            <%= checkbox.check_box(class: "checkmark")%>
            <%= checkbox.label(class: "form-check")%>
            <span class="equipment-details">
              <%= checkbox.object.details %>
            </span>
            <span class="equipment-cost">
              Cost to include: $<%= checkbox.object.price %>
            </span>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <% if booking.start_time %>
    <h2 id="booking-price">Total Price: $<%= (((booking.end_time - booking.start_time) * musician.hourly_rate).to_i / 3600) %></h2>
  <% else %>
    <h2 id="booking-price">Please enter valid start and end times to see total price</h2>
  <% end %>

  <%= f.submit 'Book!', data: { confirm: "Click OK to complete your booking. It will now appear in your \"Pending bookings\".\n\nOnce confirmed by #{musician.stage_name}, it will move to your \"Confirmed Bookings\"" }, class: 'btn' %>

<% end %>

app/views/bookings/confirmation.html.erb
<div class= 'new-booking'>

  <h2>Confirm Your Booking Details</h2>

  <%= render 'booking_form', musician: @musician, booking: @booking %>

</div>

app/views/bookings/find_musicians.html.erb
<div class="found-musicians-container">
  <% @musicians.each do |musician| %>
  <div class="partial-profile-container">
    <h2><%= musician.stage_name %></h2>
    <div class='profile-picture-container shown'>
      <% if musician.profile_picture && musician.profile_picture != "" %>
        <%= image_tag(musician.profile_picture) %>
      <% else %>
        <%= image_tag "empty_profile.png" %>
      <% end %>
    </div>
    <div class="partial-profile-details hidden">
      <h4>Bio:</h4>
      <p><%= musician.bio %></p>
      <h4>Plays: </h4>
      <ul>
        <% musician.genres.each do |genre| %>
        <li><%= genre.name %></li>
        <% end %>
      </ul>
    </div>
    <div class="partial-profile-buttons">
      <div class="partial-profile-light-buttons">
        <a class="profile-details-show shown btn btn-light" href="#">Show Details</a>
        <a class="profile-details-hide hidden btn btn-light" href="#">Hide Details</a>
        <%= link_to "View Profile", user_path(musician), target: '_blank', class: 'view-profile btn btn-light' %>
      </div>
      <%= form_for [musician, @booking], url: "/bookings/#{musician.id}/new/confirmation", method: "get" do |f| %>
      <%= hidden_field_tag('booking[event_name]', @booking.event_name) %>
      <%= hidden_field_tag('booking[start_time]', @booking.start_time) %>
      <%= hidden_field_tag('booking[end_time]', @booking.end_time) %>
      <%= hidden_field_tag('booking[address]', @booking.address) %>
      <%= hidden_field_tag('booking[party_size]', @booking.party_size) %>
      <%= hidden_field_tag('booking[age_range]', @booking.age_range) %>
      <%= f.submit 'Book Me For This Event', class: "btn book-me" %>
      <% end %>
    </div>

  </div>

  <% end %>

</div>

app/views/bookings/map.html.erb
<input id="pac-input" class="controls" type="text" placeholder="Search Box">
<div id="map"></div>


<button id="latlng_musicians"  type="button" name="button">This button does things</button>
<button id="make_marker" type="button" name="button">Make da mahka</button>
<button id="make_circle" type="button" name="button">Make da circle</button>

app/views/bookings/new.html.erb
<div class= 'new-booking'>

  <h2>Provide Some Details To Create Your Booking</h2>

  <%= render 'booking_form', musician: @musician, booking: @booking %>

</div>

app/views/bookings/new_no_musician.html.erb
<div class= 'new-booking'>
  <% if @booking.errors %>
    <% @booking.errors.messages.each do |key, value|  %>
      <% value.each do |error| %>
        <%= error %>
      <% end %>
    <% end %>
  <% end %>

  <h2>Find An Act For Your Event</h2>

  <h3>Provide some details about your event</h3>

  <div id="map_container_new_no_musician">
    <div id="map"></div>
    <input id="pac-input" class="controls" type="text" placeholder="Venue Address">
    <button id="set_radius" class="btn" type="button" name="button">Set radius</button>
    <button id="musicians_in_radius" class="btn" type="button" name="see_markers">See Musicians In My Area!</button>
  </div>


  <%= form_for @booking, url: bookings_search_musicians_path, method: 'post' do |f| %>

    <label for="radius">Desired Radius(km)</label>
    <input id="radius" type="number" name="radius" placeholder="We will only show you musicians within this distance from your event">

    <%= f.label :event_name %>
    <%= f.text_field :event_name, placeholder: "eg: 'McArthur Wedding', 'Company B Summer Jam'" %>

    <%= f.label :start_time %>
    <%= f.datetime_select :start_time, :ampm => true, :minute_step => 15 %>

    <%= f.label :end_time %>
    <%= f.datetime_select :end_time, :ampm => true, :minute_step => 15 %>

    <%= f.hidden_field :address %>

    <%= f.label :party_size %>
    <%= f.number_field :party_size, placeholder: "Approximate attendance at your event - enter only a number" %>

    <%= f.label :age_range %>
    <%= f.text_field :age_range, placeholder: "eg: '19+', 'all ages', '25 - 55'" %>

    <h3>Provide details about DJ or Band you're seeking:</h3>

    <p class='radio-buttons'>
        <%= radio_button_tag(:act_type, "dj") %>
        <%= label_tag(:act_type_dj, "DJ") %>
        <%= radio_button_tag(:act_type, "band") %>
        <%= label_tag(:act_type_band, "Band") %>
    </p>

    <%= label_tag :hourly_rate %>
    <%= text_field_tag :hourly_rate, nil, placeholder: "The maximum hourly rate you're willing to pay" %>

    <div class='genres'>
      <%= field_set_tag 'Genres' do %>
        <% collection_check_boxes(:musician, :genre_ids, Genre.all, :id, :name) do |checkbox| %>
          <div class="form-check2">
            <%= checkbox.check_box(class: "checkmark")%>
            <%= checkbox.label(class: "form-check")%>
            <span class='checkmark'></span>
          </div>
        <%end%>
      <% end %>
    </div>

    <%= f.submit 'Find Musicians!', :id=> "find_musicians_button", data: { disable_with: false }, class: 'btn' %>

  <% end %>

</div>

<div id="found_musicians_container">
</div>


  <script src="https://maps.googleapis.com/maps/api/js?libraries=geometry,places&key=AIzaSyCcNr3L8XYiOH0E81G4w_6OJjgrmNCqQrU&callback=initAutocomplete" async defer></script>