config/routes.rb
Rails.application.routes.draw do
root 'users#home'

  resources :musicians  , only: [:index]
  get 'users/updatepassword', :to => 'users#updatepassword'
  resources :users do
    resources :equipment, only: [:new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:new, :create, :update, :destroy] do
      resources :reviews, only:[:new, :create, :index]
    end
  end

  get '/bookings/:user_id/new/confirmation' => 'bookings#confirmation'
  get '/bookings/new' => 'bookings#new_no_musician'
  get '/bookings/map' => 'bookings#map'
  get '/bookings/musicians_in_radius' => 'bookings#musicians_in_radius'

  post '/bookings/search_musicians' => 'bookings#search_musicians'

  resources :sessions, only: [:new, :create]
  delete 'logout' => 'sessions#destroy'



end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Serializers::JSON
  geocoded_by :address
  after_validation :geocode
  # mount_uploader :profile_picture, ProfilePictureUploader
  has_secure_password

  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validates :kind, :presence => { message: 'specify if you are a musician or an event planner!' }
  validates :act_type, presence: true, if: :user_type_is_musician?
  validates :hourly_rate, presence: true, if: :user_type_is_musician?
  validates :hourly_rate, numericality: { greater_than: 0 }, if: :user_type_is_musician?
  validate :kind_must_only_be_musician_or_client
  validate :musician_act_type_can_only_be_dj_or_band, if: :user_type_is_musician?
  validate :musician_address_must_be_valid, if: :user_type_is_musician?

  has_many :gigs, class_name: 'Booking', foreign_key: :musician_id
  has_many :events, class_name: 'Booking', foreign_key: :client_id
  has_many :musician_reviews, class_name:'Review', foreign_key: :musician_id
  has_many :client_reviews, class_name:'Review', foreign_key: :client_id
  has_many :equipment, foreign_key: :musician_id

  has_and_belongs_to_many :genres

  def kind_must_only_be_musician_or_client
    if self[:kind] != 'musician' && self[:kind] != 'client'
      errors.add(:kind, "can only be 'musician' or 'client'")
    end
  end

  def musician_act_type_can_only_be_dj_or_band
    if self[:act_type] != 'dj' && self[:act_type] != 'band'
      errors.add(:act_type, "can only be 'dj' or 'band'")
    end
  end

  def musician_address_must_be_valid
    results = Geocoder.search(self[:address])
    unless results.any?
      errors.add(:address, 'must be valid')
    end
  end

  def user_type_is_musician?
    if self[:kind] == 'musician'
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_user_profile_owner, only: [:edit, :update, :destroy]
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

  def index
    @users = User.where('kind = ?', 'musician')
    @users = if params[:term]
      User.where('first_name LIKE ? OR last_name LIKE ? OR stage_name LIKE ?', "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%")
    else
      User.where('kind = ?', 'musician')
    end
    if @users==[]
      flash.now[:alert] = "No search results found. Please try again."
    end
  end

  def home
    render 'home', layout: false
  end

  def show
    @user = User.find(params[:id])
    @review = Review.new
    if @user.kind == 'musician'
      @review = @user.musician_reviews.new
      @reviews = @user.musician_reviews
      @genres = @user.genres
      if current_user  # what if logged in as musician?, do we add && current_user.kind == 'client'?
        @review.client_id = current_user.id # not sure this line makes sense
        @pendingbookings = current_user.gigs.where('confirmed = ?', false)
        @confirmedbookings = current_user.gigs.where('confirmed = ? AND end_time > ?', true, Time.now)
        @pastbookings = current_user.gigs.where('confirmed = ? AND end_time < ?', true, Time.now)
      end
    elsif @user.kind == 'client'
      @review = @user.client_reviews.new
      @reviews = @user.client_reviews
      if current_user && current_user == @user
        @pendingbookings = current_user.events.where('confirmed = ?', false)
        @confirmedbookings = current_user.events.where('confirmed = ? AND end_time > ?', true, Time.now)
        @pastbookings = current_user.events.where('confirmed = ? AND end_time < ?', true, Time.now)
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.kind = params[:kind]
    @user.act_type = params[:act_type]
    if @user.save
      session[:user_id] = @user.id
      if @user.kind == 'client'
        redirect_to bookings_new_path
      elsif @user.kind == 'musician'
        redirect_to user_path(@user)
      end
    else
      flash.now[:alert] = @user.errors.full_messages
      render "new"
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_url
    else
      flash.now[:alert] = @user.errors.full_messages
      render 'edit'
    end
  end

  def updatepassword
    @user = current_user
    render "updatepassword"
  end


  def destroy

  end

  def ensure_user_profile_owner
    @user = User.find(params[:id])
    if session[:user_id] != @user.id
      flash[:alert] = ["This is not your profile"]
      redirect_to users_url
    end
  end


  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :bio, :profile_picture, :stage_name, :hourly_rate, :address, genre_ids: [])
  end

  def self.search(term)
    if term
      where("title ILIKE ?", "%#{term}%")
    else
      all
    end
  end

  private

  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bookings.js.erb
<script>
document.addEventListener("turbolinks:load", function() {
  if (document.body.id != 'users_show')
    return

  var confirmBookings = document.querySelectorAll('.confirm_booking');

  confirmBookings.forEach(function(confirmBooking){
    confirmBooking.addEventListener('click', function(e) {
      var bookingId = e.target.dataset.booking_id;
      var url = '/users/<%= @user.id %>/bookings/' + bookingId
      var method = 'PATCH'

      fetch(url, {method})
      .then(response => response.json())
      .catch(error => console.error('error', error))
      .then(response => {
        var list = document.querySelector('#booking_' + bookingId)
        list.querySelector('.button_container').remove()
        list.querySelector('.button_container').remove()
        confirmed_bookings.prepend(list);
        console.log('Success:', response)
      })
    })
  })

  var rejectBooking = document.querySelectorAll('.reject_booking');

  rejectBooking.forEach(function(rejectBooking){
    rejectBooking.addEventListener('click',function(e){
      var bookingId = e.target.dataset.booking_id;

      fetch('/users/<%= @user.id %>/bookings/' + bookingId, {method:'DELETE'})
      .then(response => response.json())
      .catch(error => console.error('error', error))
      .then(response => {
        console.log('success')
        var list = document.querySelector('#booking_' + bookingId)
        list.remove()
      })
    });
  });
});
</script>

app/views/users/_client_details_form.html.erb
<h2>Please provide/update your profile information</h2>

<%= form_for(user, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>

  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </p>

  <p>
    <% if @user.profile_picture %>
      <%= image_tag(@user.profile_picture) %>
    <% end %>
    <%= f.label :profile_picture %>
    <%= f.file_field :profile_picture, placeholder: "Upload a profile picture" %>
  </p>


  <%= f.submit 'Update', class: 'btn' %>

<% end %>

app/views/users/_client_show.html.erb
<section class='user-show client'>

  <div class="profile-picture">
    <% if @user.profile_picture && @user.profile_picture != "" %>
      <%= image_tag(@user.profile_picture) %>
    <% else %>
      <%= image_tag "empty_profile.png" %>
    <% end %>
    <% if current_user && current_user.id == @user.id %>
      <div class='edit-profile'>
        <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-light"%>
        <%= link_to 'Update Password', users_updatepassword_path, class: "btn btn-light"%>
      </div>
    <% end %>
  </div>

  <div class='profile-info'>
    <h3 class='profile-name'> <%= @user.first_name %> <%= @user.last_name %></h2>
    <% if @user.bio && @user.bio.length > 0 %>
      <h3>Biography</h2>
      <p><%= @user.bio %></p>
    <% end %>
  </div>
  <% if current_user && current_user.id == @user.id %>
    <div class='bookings'>
      <div class='booking-list'>
        <h3>My Pending Bookings:</h3>
        <div class="details">
          <% @pendingbookings.each do |booking| %>
            <h4><%= booking.event_name %></h4>
            <ul id="booking_<%= booking.id %>">
              <li>Musician name: <%= link_to booking.musician.stage_name, user_path(booking.musician) %></li>
              <li>Address: <%= booking.address %></li>
              <li>Contact email: <%= booking.musician.email %></li>
              <li>Start Time: <%= booking.start_time %></li>
              <li>End Time: <%= booking.end_time %></li>
              <li>Age Range: <%= booking.age_range %></li>
              <li>Party Size: <%= booking.party_size %></li>
              <li>Total Price: $<%= (((booking.end_time - booking.start_time) * booking.musician.hourly_rate) / 3600) + (booking.equipment.inject(0) { |sum, equip| sum + equip.price }) %></li>
            </ul>
            <% if booking.equipment.any?  %>
              <h4>Equipment Requested:</h4>
              <ul>
                <% booking.equipment.each do |equip| %>
                <li><%= equip.category %> for $<%= equip.price %></li>
                <% end %>
              </ul>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class='booking-list'>
        <h3>My Confirmed Bookings:</h3>
        <div class="details">
          <% @confirmedbookings.each do |booking| %>
            <h4><%= booking.event_name %></h4>
            <ul id="booking_<%= booking.id %>">
              <li>Musician name: <%= link_to booking.musician.stage_name, user_path(booking.musician) %></li>
              <li>Address: <%= booking.address %></li>
              <li>Contact email: <%= booking.musician.email %></li>
              <li>Start Time: <%= booking.start_time %></li>
              <li>End Time: <%= booking.end_time %></li>
              <li>Age Range: <%= booking.age_range %></li>
              <li>Party Size: <%= booking.party_size %></li>
              <li>Total Price: $<%= (((booking.end_time - booking.start_time) * booking.musician.hourly_rate) / 3600) + (booking.equipment.inject(0) { |sum, equip| sum + equip.price }) %></li>
            </ul>
            <% if booking.equipment.any?  %>
              <h4>Equipment Requested:</h4>
              <ul>
                <% booking.equipment.each do |equip| %>
                <li><%= equip.category %> for $<%= equip.price %></li>
                <% end %>
              </ul>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="booking-list">
        <h3>My Past Bookings:</h3>
        <div class="details" id="past_bookings">
          <% @pastbookings.each do |booking| %>
            <h4><%= booking.event_name %></h4>
            <ul id="booking_<%= booking.id %>"
              <li>Musician name: <%= link_to booking.musician.stage_name, user_path(booking.musician) %></li>
              <li>Address: <%= booking.address %></li>
              <li>Contact email: <%= booking.musician.email %></li>
              <li>Start Time: <%= booking.start_time %></li>
              <li>End Time: <%= booking.end_time %></li>
              <li>Age Range: <%= booking.age_range %></li>
              <li>Party Size: <%= booking.party_size %></li>
              <li>Total Price: $<%= (((booking.end_time - booking.start_time) * booking.musician.hourly_rate) / 3600) + (booking.equipment.inject(0) { |sum, equip| sum + equip.price }) %></li>
            </ul>
            <% if !booking.review || booking.review.musician_reviewed == false %>
               <div class="write_review btn">
                 <%= link_to 'Write review', new_user_booking_review_path(@user, booking) %>
                 <div class="review_form hidden">
                   <%= form_for(@review, :url => user_booking_reviews_path(@user, booking)) do |f|%>
                     <button type="button" class="close">x</button>
                     <p>
                       <%= f.label :review_for_musician, "Review for: #{booking.musician.first_name}" %>
                       <%= f.text_area :musicians_review, rows: "7", class: "review_text_box" %>
                     </p>
                     <p>
                       <%= f.submit %>
                     </p>
                   <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
          <%= render 'bookings.js' %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="reviews">
    <h2>Reviews for <%= @user.first_name %>:</h2>
    <ul>
      <% @user.events.each do |event| %>
        <% if event.review %>
          <li><%= event.review.musician.stage_name %> Says: '<%= event.review.clients_review %>'</li>
        <% end %>
      <% end %>
    </ul>
  </div>
</section>

app/views/users/_musician_details_form.html.erb
<section class='signup-form'>
  <div class='form-wrapper'>
    <h2>Update My Profile</h2>

  <%= form_for(user, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
    <p>
      <%= f.label "Your Band/DJ Name" %>
      <%= f.text_field :stage_name %>
    </p>

    <p>
      <%= f.label :bio %>
      <%= f.text_area :bio %>
    </p>

    <p>
      <% if @user.profile_picture %>
        <%= image_tag(@user.profile_picture) %>
      <% end %>
      <%= f.label :profile_picture %>
      <%= f.file_field :profile_picture, placeholder: "Upload a profile picture" %>
    </p>

    <p>
      <%= f.label :hourly_rate %>
      <%= f.text_field :hourly_rate %>
    </p>

    <div class='genres'>
      <%= field_set_tag 'Genres' do %>
      <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) %>
      <% end %>
    </div>

    <p>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </p>

    <p>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </p>

    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </p>


    <%= f.submit 'Update', class: 'btn' %>

  <% end %>
  </div>
</section>

app/views/users/_musician_show.html.erb
<section class='user-show musician'>

  <div class="profile-picture">
    <% if @user.profile_picture && @user.profile_picture != "" %>
      <%= image_tag(@user.profile_picture) %>
    <% else %>
      <%= image_tag "empty_profile.png" %>
    <% end %>
    <% if current_user && current_user.id == @user.id %>
      <div class='edit-profile'>
        <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-light"%>
        <%= link_to 'Update Password', users_updatepassword_path, class: "btn btn-light"%>
      </div>
    <% end %>
  </div>

  <div class='profile-info'>
    <h1><%= @user.stage_name %></h1>

    <h3>Act Type: <%= @user.act_type.capitalize %></h3>

    <p class='profile-name'>Artist <%= @user.first_name %> <%= @user.last_name %></p>
    <% if current_user %>
      <p><%= @user.email %></p>
    <% end %>
      <h3>Biography</h3>
      <p><%= @user.bio %></p>
      <p> Rate: $<%= @user.hourly_rate %>0 /hour</p>
      <% if @genres.any? %>
    <div class="genres">
      <h3>My Genres:</h3>
      <ul>
        <% @genres.each do |genre| %>
          <li><%= genre.name %></li>
        <% end %>
      </ul>
    </div>
    <div class="equipment">
      <% if @user.equipment.any? %>
        <h3>My available equipment:</h3>
        <% @user.equipment.each do |equipment| %>
          <p><strong>Item: </strong><%= equipment.category %></p>
          <p><strong>Details: </strong><%= equipment.details %></p>
          <p><strong>Cost to include: </strong>$<%= equipment.price %></p>
        <% end %>
      <% end %>
      <% if @user == current_user %>
      <%= link_to "Add Equipment", new_user_equipment_path(@user), class: "btn btn-light" %>
      <% end %>
    </div>
  <% end %>

    <div class='book-button'>
    <% if current_user && current_user.kind == 'client' %>
      <%= link_to 'Book Me Now!', new_user_booking_path(@user), class: 'btn' %>
    <% end %>
    </div>
  </div>

  <% if current_user && current_user.id == @user.id %>
    <div class='bookings'>
      <div class='booking-list'>
        <h3>My Pending Bookings:</h3>
        <div class="details">
          <% @pendingbookings.each do |booking| %>
            <ul id="booking_<%= booking.id %>">
              <h4><%= booking.event_name %></h4>
              <li>Client name: <%= link_to booking.client.first_name, user_path(booking.client) %></li>
              <li>Address: <%= booking.address %></li>
              <li>Contact email: <%= booking.client.email %></li>
              <li>Start Time: <%= booking.start_time %></li>
              <li>End Time: <%= booking.end_time %></li>
              <li>Age Range: <%= booking.age_range %></li>
              <li>Party Size: <%= booking.party_size %></li>
              <li>Total Price: $<%= (((booking.end_time - booking.start_time) * booking.musician.hourly_rate) / 3600) + (booking.equipment.inject(0) { |sum, equip| sum + equip.price }) %></li>
              <% if booking.equipment.any?  %>
                <h4>Equipment Requested:</h4>
                  <% booking.equipment.each do |equip| %>
                  <li><%= equip.category %> for $<%= equip.price %></li>
                  <% end %>
              <% end %>
              <li class="button_container"><button class="confirm_booking btn" type="button" name="confirm_booking" data-booking_id="<%= booking.id %>">Confirm!</button></li>
              <li class="button_container"><button class="reject_booking btn btn-light" type="button" name="reject_booking" data-booking_id="<%= booking.id %>">Reject</button></li>
            </ul>
          <% end %>
        </div>
      </div>
      <div class='booking-list'>
        <h3>My Confirmed Bookings:</h3>
        <div class="details" id="confirmed_bookings">
          <% @confirmedbookings.each do |booking| %>
            <ul id="booking_<%= booking.id %>">
              <h4><%= booking.event_name %></h4>
              <li>Client name: <%= link_to booking.client.first_name, user_path(booking.client) %></li>
              <li>Address: <%= booking.address %></li>
              <li>Contact email: <%= booking.client.email %></li>
              <li>Start Time: <%= booking.start_time %></li>
              <li>End Time: <%= booking.end_time %></li>
              <li>Age Range: <%= booking.age_range %></li>
              <li>Party Size: <%= booking.party_size %></li>
              <li>Total Price: $<%= (((booking.end_time - booking.start_time) * booking.musician.hourly_rate) / 3600) + (booking.equipment.inject(0) { |sum, equip| sum + equip.price }) %></li>
            </ul>
            <% if booking.equipment.any?  %>
              <h4>Equipment Requested:</h4>
              <ul>
                <% booking.equipment.each do |equip| %>
                <li><%= equip.category %> for $<%= equip.price %></li>
                <% end %>
              </ul>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="booking-list">
        <h3>My Past Bookings:</h3>
        <div class="details" id="past_bookings">
          <% @pastbookings.each do |booking| %>
            <h4><%= booking.event_name %></h4>
            <ul id="booking_<%= booking.id %>"
              <li>Client name: <%= link_to booking.client.first_name, user_path(booking.client) %></li>
              <li>Address: <%= booking.address %></li>
              <li>Contact email: <%= booking.client.email %></li>
              <li>Start Time: <%= booking.start_time %></li>
              <li>End Time: <%= booking.end_time %></li>
              <li>Age Range: <%= booking.age_range %></li>
              <li>Party Size: <%= booking.party_size %></li>
                <li>Total Price: $<%= (((booking.end_time - booking.start_time) * booking.musician.hourly_rate) / 3600) + (booking.equipment.inject(0) { |sum, equip| sum + equip.price }) %></li>
            </ul>
            <% if !booking.review || booking.review.client_reviewed == false %>
              <div class="write_review btn">
                <%= link_to 'Write review', new_user_booking_review_path(@user, booking) %>
                <div class="review_form hidden">
                  <%= form_for(@review, :url => user_booking_reviews_path(@user, booking)) do |f|%>
                    <button type="button" class="close">x</button>
                    <p>
                      <%= f.label :clients_review, "Review for: #{booking.client.first_name}" %>
                      <%= f.text_area :clients_review, rows: "7", class: "review_text_box" %>
                    </p>
                    <p>
                      <%= f.submit %>
                    </p>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
          <%= render 'bookings.js' %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="reviews">
    <h2>Reviews for <%= @user.stage_name %>:</h2>
    <ul>
      <% @user.gigs.each do |gig| %>
        <% if gig.review %>
          <li><%= gig.review.client.first_name %> Says: '<%= gig.review.musicians_review %>'</li>
        <% end %>
      <% end %>
    </ul>
  </div>
</section>

app/views/users/_user_form.html.erb
<%= form_for user do |f| %>

  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </p>

  <p>
    <%= f.label :profile_picture %>
    <%= f.text_field :profile_picture %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>


  <%= f.submit 'Update' %>

<% end %>

app/views/users/edit.html.erb
<% if @user.kind == 'musician' %>
  <%= render 'musician_details_form', user: @user  %>
<% elsif @user.kind == 'client' %>
  <%= render 'client_details_form', user: @user  %>
<% end %>

app/views/users/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayMyParty</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id=<%="#{params[:controller]}_#{params[:action]}"%>>
    <div id="body-container">
      <header class='header'>
        <div class="logo">
          <div class="pmplogo">
            <%= image_tag "logo.jpg"%>
          </div>
          <h1>
            <%= link_to 'PlayMyParty', root_path %>
          </h1>
        </div>
        <nav class='layout-links'>
          <div class="nav-wrap">
            <%= link_to "Browse Musicians", users_path %>
            <% if current_user %>
            <%= link_to "Sign Out", logout_path, method: :delete %>
            <%= link_to "My Profile", current_user%>
            <% else %>
            <%= link_to "Register / Sign Up", new_user_path %>
            <%= link_to "Log In", new_session_path%>
            <% end %>
            <% if current_user && current_user.kind == "client" %>
            <%= link_to "Create New Booking", bookings_new_path %>
            <% end %>
            <div class='search'>
              <%= form_tag(users_path, :method => "get", id: "search-form") do %>
              <%= text_field_tag :term, params[:term], placeholder: "Find an artist" %>
              <% end %>
              <%= submit_tag "Search", name: nil, class: "btn" %>
            </div>
          </div>
        </nav>
      </header>

      <main id="home-main">
        <a class='hp-link-left home-link client' href="users/">Event Organizer</a>
        <a class='hp-link-right home-link musician' href="/users/new">Musician</a>
      </main>
      <footer class="footer">
        <p>PlayMyParty ©2018</p>
      </footer>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<section class='index-musicians'>
  <% @users.each do |user| %>
  <div class="partial-profile-container">
    <h2><%= user.stage_name %></h2>
    <div class='profile-picture-container shown'>
      <% if user.profile_picture %>
        <%= image_tag(user.profile_picture) %>
      <% else %>
        <%= image_tag "empty_profile.png" %>
      <% end %>
    </div>
    <div class="partial-profile-details hidden">
      <h4>Bio:</h4>
      <p><%= user.bio %></p>
      <h4>Plays: </h4>
      <ul>
        <% user.genres.each do |genre| %>
        <li><%= genre.name %></li>
        <% end %>
      </ul>
    </div>
    <div class="partial-profile-buttons">
      <div class="partial-profile-light-buttons">
        <a class="profile-details-show shown btn btn-light" href="#">Show Details</a>
        <a class="profile-details-hide hidden btn btn-light" href="#">Hide Details</a>
        <%= link_to "View Profile", user_path(user), class: 'view-profile btn btn-light' %>
      </div>
    <% if current_user && current_user.kind == 'client' %>
      <%= link_to 'Book Me For An Event', new_user_booking_path(user), class: "btn book-me" %>
    <% end %>
    </div>
  </div>
  <% end %>
</section>

app/views/users/show.html.erb
<% if @user.kind == 'client' %>
<%=  render 'client_show' %>
<% elsif @user.kind == 'musician' %>
<%=  render 'musician_show' %>
<% end %>

app/views/users/updatepassword.html.erb
<%= form_for @user do |f| %>

<h2>Update Password</h2>
<p>
<%= f.label :password  %>
<%= f.password_field :password %>
</p>
<p>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</p>
<div class='update-password'>
  <%= f.submit 'Update Password' %>
</div>
<% end %>