config/routes.rb
Rails.application.routes.draw do
root 'users#home'

  resources :musicians  , only: [:index]
  get 'users/updatepassword', :to => 'users#updatepassword'
  resources :users do
    resources :equipment, only: [:new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:new, :create, :update, :destroy] do
      resources :reviews, only:[:new, :create, :index]
    end
  end

  get '/bookings/:user_id/new/confirmation' => 'bookings#confirmation'
  get '/bookings/new' => 'bookings#new_no_musician'
  get '/bookings/map' => 'bookings#map'
  get '/bookings/musicians_in_radius' => 'bookings#musicians_in_radius'

  post '/bookings/search_musicians' => 'bookings#search_musicians'

  resources :sessions, only: [:new, :create]
  delete 'logout' => 'sessions#destroy'



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayMyParty</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id=<%="#{params[:controller]}_#{params[:action]}"%>>
    <div id="body-container">
      <header class='header'>
        <div class="logo">
          <div class="pmplogo">
            <%= image_tag "logo.jpg"%>
          </div>
          <h1>
            <%= link_to 'PlayMyParty', root_path %>
          </h1>
        </div>
        <nav class='layout-links'>
          <div class="nav-wrap">
            <%= link_to "Browse Musicians", users_path %>
            <% if current_user %>
            <%= link_to "Sign Out", logout_path, method: :delete %>
            <%= link_to "My Profile", current_user%>
            <% else %>
            <%= link_to "Register / Sign Up", new_user_path %>
            <%= link_to "Log In", new_session_path%>
            <% end %>
            <% if current_user && current_user.kind == "client" %>
            <%= link_to "Create New Booking", bookings_new_path %>
            <% end %>
            <div class='search'>
              <%= form_tag(users_path, :method => "get", id: "search-form") do %>
              <%= text_field_tag :term, params[:term], placeholder: "Find an artist" %>
              <% end %>
              <%= submit_tag "Search", name: nil, class: "btn" %>
            </div>
          </div>
        </nav>
      </header>

      <main>
        <% if flash && flash.any?  %>
          <div class="flash">
            <% flash.each do |key, message| %>
              <h4><% key %></h4>
              <% if message && message.class != String && message.any?  %>
              <% message.each do |sub_message|  %>
              <h5><%= sub_message %></h5>
              <% end %>
              <% else %>
              <h5><%= message %></h5>
              <% end  %>
            <% end %>
          </div>
        <% end %>

        <%= yield %>
      </main>
      <footer class="footer">
        <p>PlayMyParty ©2018</p>
      </footer>
    </div>
  </body>
</html>